# Change these first
owner: ServeRest # Your GitHub username
repo: status-agilizei # Your Github repository name

# Add your sites here
sites:
  - name: api.agilizei.com/
    url: http://serverest-api-agilizei-com.umbler.net/
    maxResponseTime: 1500
  - name: API /usuarios
    url: http://serverest-api-agilizei-com.umbler.net/usuarios
    headers:
      - "monitor: uptime"
    maxResponseTime: 600
  - name: API /carrinhos
    url: http://serverest-api-agilizei-com.umbler.net/carrinhos
    headers:
      - "monitor: uptime"
    maxResponseTime: 600
  - name: API /produtos
    url: http://serverest-api-agilizei-com.umbler.net/produtos
    headers:
      - "monitor: uptime"
    maxResponseTime: 600

assignees:
  - PauloGoncalvesBH

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: serverest-status.agilizei.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status-agilizei
  logoUrl: https://agilizei.files.wordpress.com/2020/08/cropped-agilizei.png
  icon: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - ServeRest no Agilizei
  navbar:
    - title: Status
      href: /
    - title: ServeRest
      href: https://github.com/ServeRest

workflowSchedule:
  graphs: "0 */12 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
